pipeline:
  test:
    image: rakuland/raku:latest
    when:
      event: [push, pull_request]
      branch: main
    commands:
      - raku -v
      - zef install --verbose --test-depends --deps-only --/test .
      - prove6 -v -I.
